version: "3"
services:
  postgis:
    image: postgis/postgis
    profiles:
      - "database"
    restart: always
    container_name: ${POSTGRES_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS} # 25% of available RAM recommended
    command: postgres -c "max_connections=${POSTGRES_MAX_CONNECTIONS}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      # - ./config/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./data:/var/lib/postgresql/data
      - postgis_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  app-network:
    driver: bridge
volumes:
  postgis_data:
